# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'sensor-ios' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for sensor-ios
	pod 'Alamofire', '~> 3.5'
	pod 'AlamofireImage', '~> 2.5'
	pod 'AlamofireObjectMapper', '~>3.0'
	pod 'BrightFutures', '~> 3.3.0'
	pod 'CircleSlider', '~> 0.4.0'
	pod 'FirebaseUI', '~> 1.0'
	pod 'ObjectMapper', '~> 1.5'
	pod 'RealmSwift', '~> 1.1.0'
	pod 'RZTransitions', '~> 1.2.1'
	pod 'Toast-Swift', '~> 1.3.0'

  target 'sensor-iosTests' do
    inherit! :search_paths
    # Pods for testing
		pod 'Firebase'
  end

  target 'sensor-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
